eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
server:
  port: 8761
spring:
  output:
    ansi:
      enabled: always
#spring.output.ansi.enabled=always 控制台彩色输出.
#eureka.client.register-with-eureka: 该参数代表该Eureka应用（包括注册中心）是否注册到注册中心中，
#如果只是一个单一注册中心，那么把该参数设置为false,代表不向注册中心注册自己。
#如果是搭建高可用的集群注册中心，则该属性设置为true。该属性值默认true。
#eureka.client.fetch-registry ： 该参数代表是否需要检索服务，如果是单一注册中心则不需要去检索服务，则设置为false。该参数默认值为true。
#eureka.client.serviceUrl.defaultZone: 该参数指定默认注册中心的注册地址，其他的微服务应用就是通过该属性值来注册服务。